services:
  backend:
    build:
      context: ./SENGPRJ_Group6
      dockerfile: Dockerfile
    container_name: leo-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./SENGPRJ_Group6_FrontendPart/app
      dockerfile: Dockerfile
      args:
        - VITE_API=http://13.53.169.202:8080
    container_name: leo-frontend
    ports:
      - "5174:5173"
    depends_on:
      - backend
